#!/bin/bash

echo "$1" >> /home/xaloc/intentos
FILE="$HOME/.config/pulse/daemon.conf"

if [ ! -f $FILE ]; then
    echo "$FILE not found. Creating"
    echo "default-sample-rate = $1" >> $FILE
    exit
fi

LINE=$(sed '/default-sample-rate/!d;=' $FILE | head -n 1)

if [ -z "$LINE" ]; then
    echo "Sample rate added to the config file."
    echo "default-sample-rate = $1" >> $FILE
fi

if [ -n "$LINE" ]; then
    echo "Sample rate changed in the config file."
    newLine="default-sample-rate = $1"
    sed -i "${LINE}s/.*/${newLine}/" $FILE
fi
